import { Inter,Montserrat} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/Components/Header";

const inter = Montserrat({ subsets: ["latin"] });
//Inter is used to change the font , a inbuilt feature provided by next.js


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}</body>
      </html>
    </ClerkProvider>
  );
}
